import org.junit.Test;

import de.uni_stuttgart.ipvs.occpancy_monitoring.Library;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Qaid' at '8/4/16 9:29 PM' with Gradle 2.14
 *
 * @author Qaid, @date 8/4/16 9:29 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
